# -*- coding: utf-8 -*-
"""Xformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gWfqTFTcCglQsPI_xoeM8TKZWYqU5XL
"""

# -------------------------------
# Time-Series Stock Price Forecasting with Transformers
# Google Colab Ready
# -------------------------------

# 1️⃣ Install PyTorch + xFormers + dependencies
!pip install torch==2.8.0+cu128 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
!pip install xformers yfinance matplotlib seaborn scikit-learn pandas numpy

# 2️⃣ Imports
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
import xformers.ops as xops
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# 3️⃣ Data Acquisition & Feature Engineering
def get_stock_data(ticker="AAPL", start="2015-01-01", end="2025-01-01"):
    df = yf.download(ticker, start=start, end=end)
    df = df[['Close']]
    df['Return'] = df['Close'].pct_change().fillna(0)
    df['MA10'] = df['Close'].rolling(10).mean().bfill()
    df['Volatility'] = df['Close'].rolling(5).std().bfill()
    df = df.dropna()
    return df

df = get_stock_data()
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

# 4️⃣ Sequence Preparation
SEQ_LENGTH = 30
def create_sequences(data, seq_length=SEQ_LENGTH):
    X, y = [], []
    for i in range(len(data)-seq_length):
        X.append(data[i:i+seq_length])
        y.append(data[i+seq_length][0])  # predict Close price
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data, SEQ_LENGTH)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, shuffle=False)

X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).unsqueeze(-1)
X_val = torch.tensor(X_val, dtype=torch.float32)
y_val = torch.tensor(y_val, dtype=torch.float32).unsqueeze(-1)

# -------------------------------
# 5️⃣ Transformer Model
# -------------------------------
class TimeSeriesTransformer(nn.Module):
    def __init__(self, feature_size, num_layers=3, num_heads=4, dropout=0.1):
        super().__init__()
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=feature_size,
            nhead=num_heads,
            dropout=dropout,
            batch_first=True,
            activation='relu'
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.linear = nn.Linear(feature_size, 1)

    def forward(self, x):
        x = self.transformer(x)
        out = self.linear(x[:, -1, :])
        return out

feature_size = X_train.shape[2]
model = TimeSeriesTransformer(feature_size=feature_size, num_layers=3, num_heads=4)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# -------------------------------
# 6️⃣ Training Setup
# -------------------------------
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=5e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5)

train_dataset = TensorDataset(X_train, y_train)
val_dataset = TensorDataset(X_val, y_val)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64)

best_val_loss = np.inf
patience_counter = 0
EARLY_STOPPING_PATIENCE = 10
EPOCHS = 100

def direction_accuracy(y_true, y_pred):
    y_true_dir = (y_true[1:] - y_true[:-1]) > 0
    y_pred_dir = (y_pred[1:] - y_true[:-1]) > 0
    return (y_true_dir == y_pred_dir).float().mean().item() * 100

# -------------------------------
# 7️⃣ Training Loop
# -------------------------------
for epoch in range(EPOCHS):
    model.train()
    train_loss = 0
    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        out = model(xb)
        loss = criterion(out, yb)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    model.eval()
    val_loss = 0
    preds = []
    with torch.no_grad():
        for xb, yb in val_loader:
            xb, yb = xb.to(device), yb.to(device)
            out = model(xb)
            val_loss += criterion(out, yb).item()
            preds.append(out.cpu())
    preds = torch.cat(preds)
    acc = direction_accuracy(y_val, preds)

    scheduler.step(val_loss)

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pth")
        patience_counter = 0
    else:
        patience_counter += 1

    if patience_counter > EARLY_STOPPING_PATIENCE:
        print(f"Early stopping at epoch {epoch}")
        break

    if epoch % 5 == 0 or epoch == EPOCHS-1:
        print(f"Epoch {epoch}: Train Loss={train_loss/len(train_loader):.6f}, "
              f"Val Loss={val_loss/len(val_loader):.6f}, Direction Accuracy={acc:.2f}%")

# -------------------------------
# 8️⃣ Forecasting & Visualization
# -------------------------------
model.load_state_dict(torch.load("best_model.pth"))
model.eval()
with torch.no_grad():
    y_pred = model(X_val.to(device)).cpu().numpy()

# Rescale to original price
y_val_rescaled = scaler.inverse_transform(np.concatenate([y_val.numpy(), np.zeros((len(y_val), 3))], axis=1))[:,0]
y_pred_rescaled = scaler.inverse_transform(np.concatenate([y_pred, np.zeros((len(y_pred), 3))], axis=1))[:,0]

plt.figure(figsize=(15,6))
plt.plot(y_val_rescaled, label="Actual")
plt.plot(y_pred_rescaled, label="Predicted")
plt.title("Stock Price Prediction")
plt.xlabel("Time")
plt.ylabel("Price")
plt.legend()
plt.show()