# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bitcoin_full.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bitcoin_full.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62itcoin_full.proto\"\xeb\x04\n\x0f\x42itcoinFullData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x15\n\rcurrent_price\x18\x06 \x01(\x01\x12\x12\n\nmarket_cap\x18\x07 \x01(\x01\x12\x17\n\x0fmarket_cap_rank\x18\x08 \x01(\x05\x12\x1f\n\x17\x66ully_diluted_valuation\x18\t \x01(\x01\x12\x14\n\x0ctotal_volume\x18\n \x01(\x01\x12\x10\n\x08high_24h\x18\x0b \x01(\x01\x12\x0f\n\x07low_24h\x18\x0c \x01(\x01\x12\x18\n\x10price_change_24h\x18\r \x01(\x01\x12#\n\x1bprice_change_percentage_24h\x18\x0e \x01(\x01\x12\x1d\n\x15market_cap_change_24h\x18\x0f \x01(\x01\x12(\n market_cap_change_percentage_24h\x18\x10 \x01(\x01\x12\x1a\n\x12\x63irculating_supply\x18\x11 \x01(\x01\x12\x14\n\x0ctotal_supply\x18\x12 \x01(\x01\x12\x12\n\nmax_supply\x18\x13 \x01(\x01\x12\x0b\n\x03\x61th\x18\x14 \x01(\x01\x12\x1d\n\x15\x61th_change_percentage\x18\x15 \x01(\x01\x12\x10\n\x08\x61th_date\x18\x16 \x01(\t\x12\x0b\n\x03\x61tl\x18\x17 \x01(\x01\x12\x1d\n\x15\x61tl_change_percentage\x18\x18 \x01(\x01\x12\x10\n\x08\x61tl_date\x18\x19 \x01(\t\x12\x14\n\x0clast_updated\x18\x1a \x01(\t\x12\x0e\n\x06source\x18\x1b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bitcoin_full_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BITCOINFULLDATA']._serialized_start=23
  _globals['_BITCOINFULLDATA']._serialized_end=642
# @@protoc_insertion_point(module_scope)
