FROM python:3.10-slim

RUN pip install --upgrade pip

RUN pip install \
    jupyter \
    streamlit \
    py2neo \
    pandas \
    matplotlib \
    numpy \
    pandas \
    networkx \
    requests

WORKDIR /workspace
EXPOSE 8888
EXPOSE 8501
