FROM umd-dev:latest

# Install all project-specific Python dependencies 
# pip install them every time a container starts.
RUN pip install --no-cache-dir \
    scikit-learn \
    xgboost \
    mlflow

