import pandas as pd
from typing import Tuple
def load_data(path: str) -> pd.DataFrame: ...
def basic_eda(df: pd.DataFrame) -> dict: ...
def train_test_split_xy(df: pd.DataFrame, target: str="Class") -> Tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series]: ...
def apply_smote(X_train, y_train): ...
def fit_glm(X_train, y_train): ...
def glm_residual_analysis(model, X, y): ...
def detect_anomalies_from_residuals(res_df, z_thresh=3.0): ...
def eval_metrics(y_true, y_pred, y_score=None): ...
def plot_confusion(y_true, y_pred): ...
def plot_roc(y_true, y_score): ...
