authors:
  gpsaggese:
    name: Giacinto Paolo Saggese
    description: Adjunct Professor at University of Maryland
    avatar: https://github.com/gpsaggese.png
    url: https://gpsaggese.github.io/
    email: saggese@gmail.com, gsaggese@umd.edu

  PranavShashidhara:
    name: Pranav
    description: TBD
    avatar: https://github.com/PranavShashidhara.png
    url: TBD
    email: TBD

  damiancalabresi:
    name: Damian
    description: TBD
    avatar: https://github.com/damiancalabresi.png
    url: TBD
    email: TBD
