# -*- coding: utf-8 -*-
"""Utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBpF0aqCmcuOkPrUIzUlhE_o8WO-AFXi
"""

import logging
import random
from typing import List, Tuple, Optional, Dict

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from trl import AutoModelForCausalLMWithValueHead, PPOTrainer, PPOConfig, create_reference_model

_LOG = logging.getLogger(__name__)

# #############################################################################
# Data Preprocessing Functions
# #############################################################################

def prepare_context_response_pairs(dialogs: List[Dict], context_length: int = 3) -> List[Tuple[List[str], str]]:
    """
    Convert a list of dialogues into context-response pairs for training or evaluation.
    Each dialogue entry in `dialogs` should have a 'dialog' key with a list of utterances:contentReference[oaicite:0]{index=0}.

    This function creates multiple pairs from each dialogue by taking the last 1 to `context_length`
    utterances as the context and the next utterance as the response.

    :param dialogs: list of dataset entries, each containing a 'dialog' (list of utterance strings)
    :param context_length: how many past utterances to include in context (max)
    :return: list of (context, response) pairs, where context is a list of utterances and response is a string
    """
    pairs: List[Tuple[List[str], str]] = []
    for entry in dialogs:
        conv = entry.get("dialog", entry)  # handle either dict with 'dialog' or raw list
        if not isinstance(conv, list):
            continue  # skip if dialog is missing or not a list
        n = len(conv)
        # Iterate through conversation turns, producing context-response pairs
        for i in range(1, n):
            # Determine context window for this response
            start_idx = max(0, i - context_length)
            context_utts = conv[start_idx:i]  # last up to context_length utterances before i
            response = conv[i]
            pairs.append((context_utts, response))
    return pairs

def format_context(utterances: List[str], tokenizer: AutoTokenizer) -> str:
    """
    Format a list of utterances into a single string for the model, separating turns with the EOS token.
    This helps DialoGPT identify conversation boundaries.

    :param utterances: list of utterance strings in the dialogue context
    :param tokenizer: tokenizer (with an EOS token defined) for the model
    :return: a single string with EOS tokens appended after each utterance
    """
    eos_token = tokenizer.eos_token or "<|endoftext|>"
    if not utterances:
        return eos_token  # return just EOS if no context
    # Join utterances with EOS in between, and append EOS at end to indicate end-of-context
    return eos_token.join(utterances) + eos_token

# #############################################################################
# Model and Generation Functions
# #############################################################################

def load_dialogue_model(model_name: str = "microsoft/DialoGPT-small") -> Tuple[AutoModelForCausalLM, AutoTokenizer]:
    """
    Load a pre-trained conversational model (DialoGPT) and its tokenizer.
    The model is wrapped with a value head for PPO training.

    :param model_name: name or path of the pretrained DialoGPT model
    :return: a tuple (model, tokenizer) where model is a AutoModelForCausalLMWithValueHead
    """
    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLMWithValueHead.from_pretrained(model_name)
    # Ensure tokenizer has a padding token to avoid warnings (DialoGPT uses EOS as pad)
    tokenizer.pad_token = tokenizer.eos_token
    _LOG.info("Loaded model `%s` with %s parameters", model_name, model.num_parameters()) if hasattr(model, "num_parameters") else None
    return model, tokenizer

def generate_response(model: AutoModelForCausalLM, tokenizer: AutoTokenizer, context: List[str], max_new_tokens: int = 50) -> str:
    """
    Generate a single response from the model given a dialogue context.

    :param model: the language model (with value head if PPO) to use for generation
    :param tokenizer: tokenizer for the model
    :param context: list of utterances representing the dialogue history (context)
    :param max_new_tokens: maximum number of tokens to generate for the response
    :return: the generated response text (str)
    """
    # Prepare input IDs from context
    input_text = format_context(context, tokenizer)
    input_ids = tokenizer.encode(input_text, return_tensors="pt")
    input_ids = input_ids.to(model.device)  # move to model device (GPU/CPU)
    # Generate a response
    output_ids = model.generate(
        input_ids,
        max_new_tokens=max_new_tokens,
        pad_token_id=tokenizer.eos_token_id,
        do_sample=True,  # use sampling for more natural responses
        top_p=0.9,       # nucleus sampling for diversity
        temperature=1.0
    )
    # The generated output includes the context and response; extract the response part
    generated_ids = output_ids[0][input_ids.shape[-1]:]  # exclude the context tokens
    response_text = tokenizer.decode(generated_ids, skip_special_tokens=True)
    return response_text

# #############################################################################
# Reward Calculation Functions
# #############################################################################

# Initialize a sentiment analysis pipeline (global singleton) when first needed
_sentiment_analyzer = None

def compute_reward(response_text: str, use_length_heuristic: bool = True) -> float:
    """
    Compute a scalar reward for a generated response based on its sentiment (and optionally length).
    Positive responses receive higher reward, negative responses receive lower (even negative) reward.

    The sentiment is evaluated via a pretrained sentiment classifier. An optional length heuristic can
    give a small penalty to very short responses to encourage more informative outputs.

    :param response_text: the generated response (single utterance) to evaluate
    :param use_length_heuristic: whether to adjust reward based on response length
    :return: reward value (float), typically in the range [-1.0, 1.0]
    """
    global _sentiment_analyzer
    if _sentiment_analyzer is None:
        # Load a sentiment analysis pipeline (e.g., distilbert-base-uncased-finetuned-sst-2-english)
        _sentiment_analyzer = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english", device=0 if torch.cuda.is_available() else -1)
    # Get sentiment prediction
    result = _sentiment_analyzer(response_text[:512])  # limit length for sentiment model
    label = result[0]['label']
    score = result[0]['score']
    # Base sentiment reward: +score for positive, -score for negative
    sentiment_reward = score if label == "POSITIVE" else -score
    reward = sentiment_reward
    # Optional length-based heuristic: penalize very short responses, mildly reward adequate length
    if use_length_heuristic:
        num_tokens = len(response_text.split())
        if num_tokens < 5:
            reward -= 0.2  # discourage trivially short responses
        elif num_tokens > 50:
            reward -= 0.1  # very long rambling responses might be penalized
        else:
            # small bonus for having at least a minimal length
            reward += 0.1
    return reward

# #############################################################################
# Evaluation Functions
# #############################################################################

def calculate_distinct_n(responses: List[str], n: int = 1) -> float:
    """
    Calculate the Distinct-N metric for a list of generated responses:contentReference[oaicite:1]{index=1}.
    Distinct-N is the number of unique n-grams in the responses divided by the total number of n-grams.

    :param responses: list of response strings generated by the model
    :param n: size of n-gram (e.g., 1 for distinct-1, 2 for distinct-2)
    :return: distinct-n score (fraction of unique n-grams)
    """
    if not responses:
        return 0.0
    total_ngrams = 0
    unique_ngrams = set()
    for resp in responses:
        # Tokenize by whitespace for n-grams (simple approach)
        words = resp.split()
        # Extract n-grams from the response
        for i in range(len(words) - n + 1):
            ngram = tuple(words[i:i+n])
            unique_ngrams.add(ngram)
            total_ngrams += 1
    if total_ngrams == 0:
        return 0.0
    return len(unique_ngrams) / total_ngrams

def evaluate_sentiment(responses: List[str]) -> Dict[str, float]:
    """
    Evaluate the sentiment of a list of responses, returning the proportion of positive responses and average sentiment score.

    The average sentiment score is computed by assigning +1 to a perfectly positive response and -1 to a perfectly negative response.

    :param responses: list of generated response strings
    :return: dictionary with 'positive_fraction' and 'average_score'
    """
    if not responses:
        return {"positive_fraction": 0.0, "average_score": 0.0}
    global _sentiment_analyzer
    if _sentiment_analyzer is None:
        _sentiment_analyzer = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english", device=0 if torch.cuda.is_available() else -1)
    results = _sentiment_analyzer(responses)
    positive_count = 0
    total_score = 0.0
    for res in results:
        label = res['label']
        score = res['score']
        if label == "POSITIVE":
            positive_count += 1
            total_score += score  # positive score
        else:
            total_score -= score  # negative score counts negatively
    positive_fraction = positive_count / len(responses)
    average_score = total_score / len(responses)
    return {"positive_fraction": positive_fraction, "average_score": average_score}

# #############################################################################
# PPO Training Loop Function
# #############################################################################

def train_dialogue_model(
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    contexts: List[List[str]],
    num_steps: int = 100,
    batch_size: int = 8,
    ppo_kwargs: Optional[Dict] = None
) -> AutoModelForCausalLM:
    """
    Fine-tune the dialogue model using Proximal Policy Optimization (PPO) on the given contexts.

    At each step, a batch of contexts is sampled, the model generates responses, and a reward is computed for each
    using `compute_reward`. The PPO trainer then updates the model to maximize the expected reward.

    :param model: the model to fine-tune (should already be loaded with a value head)
    :param tokenizer: tokenizer for the model
    :param contexts: list of dialogue contexts (each a list of utterances) to sample from for training
    :param num_steps: total number of PPO update steps to perform
    :param batch_size: number of context-response samples per PPO update
    :param ppo_kwargs: optional dict of additional PPOTrainer configuration (learning rate, etc.)
    :return: the fine-tuned model (updated in-place)
    """
    # Prepare reference model for KL penalty and configure PPO
    ref_model = create_reference_model(model)
    ppo_config = PPOConfig(batch_size=batch_size, **(ppo_kwargs or {}))
    trainer = PPOTrainer(ppo_config, model, ref_model, tokenizer, **(ppo_kwargs or {}))
    device = model.device

    # Training loop
    for step in range(1, num_steps + 1):
        # Sample a batch of contexts from the provided list
        batch_contexts = random.sample(contexts, batch_size) if batch_size <= len(contexts) else contexts
        query_tensors = []
        response_tensors = []
        rewards = []
        # Generate responses and compute rewards for each context in the batch
        for ctx in batch_contexts:
            # Encode context and generate response using current model
            context_text = format_context(ctx, tokenizer)
            query_tensor = tokenizer.encode(context_text, return_tensors="pt").to(device)
            # Generate a response (one sample per context)
            generated_tensor = model.generate(
                query_tensor,
                max_new_tokens=50,
                pad_token_id=tokenizer.eos_token_id,
                do_sample=True, top_p=0.9, temperature=1.0
            )
            # Extract the response portion (skip input context)
            response_tensor = generated_tensor[:, query_tensor.shape[-1]:]
            response_text = tokenizer.decode(response_tensor.squeeze(), skip_special_tokens=True)
            # Compute reward for the generated response
            reward_value = compute_reward(response_text, use_length_heuristic=True)
            query_tensors.append(query_tensor[0])
            response_tensors.append(response_tensor[0])
            rewards.append(torch.tensor(reward_value))
        # Perform one PPO update step with the collected batch
        trainer.step(query_tensors, response_tensors, rewards)
        if step % 10 == 0 or step == num_steps:
            _LOG.info("PPO training step %d/%d complete", step, num_steps)
    return model