@echo off
echo 🔄 Activating virtual environment...
call .venv\Scripts\activate

echo 🐳 Starting Docker container (PostgreSQL)...
docker start bitcoin-postgres

echo 🚀 Running Prefect ETL script...
python prefect_main.py

echo ✅ Done! Press any key to exit...
pause
